image: microsoft/dotnet:latest

stages:
    - build
    
before_script:
    - "cd gtaserver.core"
    - "dotnet restore"
    
build:
    stage: build
    script:
        - "dotnet build -r win7-x64 -c Release"
        - "dotnet build -r ubuntu.14.04-x64 -c Release"
        - "dotnet publish -r win7-x64 -c Release -o windows-Release"
        - "dotnet publish -r ubuntu.14.04-x64 -c Release -o linux-Release"
    artifacts:
        paths:
            - "windows-Release/"
            - "linux-Release/"