image: mcr.microsoft.com/dotnet/sdk:6.0

variables:
  GIT_SUBMODULE_STRATEGY: normal

stages:
    - build_server
    - plugins
    
before_script:
    # https://gitlab.com/TheIndra55/lidgren-network-gen3
    - "dotnet nuget add source https://gitlab.com/api/v4/projects/20574571/packages/nuget/index.json -n gitlab"
    
build_windows:
    stage: build_server
    # run on Windows since while crossbuilding on Linux, apphost customization doesn't work
    tags:
        - shared-windows
        - windows
    script:
        - cd gtaserver.core
        - dotnet publish -r win10-x64 -c Release -o publish/windows-Release -p:PublishSingleFile=true
    artifacts:
        paths:
            - "gtaserver.core/publish/windows-Release"

build_linux:
    stage: build_server
    script:
        - cd gtaserver.core
        - dotnet publish -r ubuntu-x64 -c Release -o publish/linux-Release
    artifacts:
        paths:
            - "gtaserver.core/publish/linux-Release"

build_linux_arm:
    stage: build_server
    when: manual
    script:
        - cd gtaserver.core
        - dotnet publish -r linux-arm -c Release -o publish/arm-Release
    artifacts:
        paths:
            - "gtaserver.core/publish/arm-Release"

build_plugins:
    stage: plugins
    script:
       - cd Race
       - dotnet publish -c Release -o publish
       - cd ../DiscordBot # hm
       - dotnet publish -c Release -o publish
    artifacts:
        paths:
            - "Race/publish/race.dll"
            - "Race/publish/race.pdb"
            - "Race/publish/Maps"
            - "DiscordBot/publish/DiscordBot.dll"
            - "DiscordBot/publish/DiscordBot.pdb"
