image: mcr.microsoft.com/dotnet/core/sdk:3.1

stages:
    - build
    
before_script:
    - "apt-get update -qq && apt-get install -y -qq zip"
    - "cd gtaserver.core"
    - "dotnet restore"
    
build_windows:
    stage: build
    script:
        # windows 7 is EOL, win10 includes win81
        - dotnet publish -r win10-x64 -c Release -o publish/windows-Release
        - zip -r publish/windows-Release.zip publish/windows-Release
    artifacts:
        paths:
            - "gtaserver.core/publish/windows-Release.zip"

build_linux:
    stage: build
    script:
        - dotnet publish -r ubuntu-x64 -c Release -o publish/linux-Release
        - zip -r publish/linux-Release.zip publish/linux-Release
    artifacts:
        paths:
            - "gtaserver.core/publish/linux-Release.zip"

build_linux_arm:
    stage: build
    script:
        - dotnet publish -r linux-arm -c Release -o publish/arm-Release
        - zip -r publish/arm-Release.zip publish/arm-Release
    artifacts:
        paths:
            - "gtaserver.core/publish/arm-Release.zip"
