image: microsoft/dotnet:latest

stages:
    - build
    
before_script:
    - "apt-get update -qq && apt-get install -y -qq zip"
    - "cd gtaserver.core"
    - "dotnet restore"
    
build:
    stage: build
    script:
        - "dotnet build -r win7-x64 -c Release"
        - "dotnet build -r ubuntu.14.04-x64 -c Release"
        - "dotnet publish -r win7-x64 -c Release -o windows-Release"
        - "dotnet publish -r ubuntu.14.04-x64 -c Release -o linux-Release" 
        # add gamemodes to server
        - "mkdir publish\windows-Release\Gamemodes"
        - "mkdir publish\linux-Release\Gamemodes\"
        - "cd ../Freeroam/ && dotnet build -c Release && dotnet publish --no-dependencies -o ..\gtaserver.core\publish\windows-Release\Gamemodes"
        - "cd ../Freeroam/ && dotnet build -c Release && dotnet publish --no-dependencies -o ..\gtaserver.core\publish\linux-Release\Gamemodes\"
        - "cd ../gtaserver.core"
        # zip the builds
        - "zip -r windows-Release.zip windows-Release"
        - "zip -r linux-Release.zip linux-Release"
    artifacts:
        paths:
            - "gtaserver.core/windows-Release.zip"
            - "gtaserver.core/linux-Release.zip"