image: mcr.microsoft.com/dotnet/sdk:5.0.102-ca-patch-buster-slim

stages:
    - build
    - plugins
    
before_script:
    # https://gitlab.com/TheIndra55/lidgren-network-gen3
    - "dotnet nuget add source https://gitlab.com/api/v4/projects/20574571/packages/nuget/index.json -n gitlab"
    - "cd gtaserver.core"
    - "dotnet restore"
    
build_windows:
    stage: build
    # run in Windows since on crossbuilding on Linux apphost customization doesn't work
    tags:
        - shared-windows
        - windows
        - windows-2004
    script:
        # windows 7 is EOL, win10 includes win81
        #- dotnet publish -r win10-x64 -c Release -o publish/windows-Release
        - dotnet publish -r win10-x64 --self-contained -c Release -o publish/windows-Release -p:PublishSingleFile=true -p:EnableCompressionInSingleFile=true
    artifacts:
        paths:
            - "gtaserver.core/publish/windows-Release"

build_linux:
    stage: build
    script:
        - dotnet publish -r ubuntu-x64 -c Release -o publish/linux-Release
    artifacts:
        paths:
            - "gtaserver.core/publish/linux-Release"

build_linux_arm:
    stage: build
    when: manual
    script:
        - dotnet publish -r linux-arm -c Release -o publish/arm-Release
    artifacts:
        paths:
            - "gtaserver.core/publish/arm-Release"

build_plugins:
    stage: plugins
    script:
       - cd ../Race2 # are we still in gtaserver.core directory from before_script?
       - dotnet publish -c Release -o publish
       - cd ../DiscordBot # hm
       - dotnet publish -c Release -o publish
    artifacts:
        paths:
            - "Race2/publish/race.dll"
            - "Race2/publish/race.pdb"
            - "Race2/publish/Maps"
            - "DiscordBot/publish/DiscordBot.dll"
            - "DiscordBot/publish/DiscordBot.pdb"
