image: microsoft/dotnet:latest

stages:
    - build
    
before_script:
    - "cd gtaserver.core"
    - "dotnet restore"
    
build:
    stage: build
    script:
        - "cd gtaserver.core"
        - "dotnet build -r win7-x64 -c Release"
        - "dotnet build -r ubuntu.14.04-x64 -c Release"