image: mcr.microsoft.com/dotnet/sdk:6.0

variables:
  GIT_SUBMODULE_STRATEGY: normal

stages:
    - build_server
    - build_client
    - plugins
    
before_script:
    # https://gitlab.com/TheIndra55/lidgren-network-gen3
    - "dotnet nuget add source https://gitlab.com/api/v4/projects/20574571/packages/nuget/index.json -n gitlab"
    
build_windows:
    stage: build_server
    # run in Windows since on crossbuilding on Linux apphost customization doesn't work
    tags:
        - shared-windows
        - windows
    script:
        - cd gtaserver.core
        # windows 7 is EOL, win10 includes win81
        #- dotnet publish -r win10-x64 -c Release -o publish/windows-Release
        - dotnet publish -r win10-x64 -c Release -o publish/windows-Release -p:PublishSingleFile=true
    artifacts:
        paths:
            - "gtaserver.core/publish/windows-Release"

build_client:
    stage: build_client
    when: manual
    tags:
        - shared-windows
        - windows
        - windows-22h2
    script:
        - '"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat"'
        - msbuild /t:restore
        - cd NativeUI
        - msbuild /t:build /restore /p:Configuration=Release /p:OutputPath=bin\Release
        - cd ../Client
        - msbuild /t:build /restore /p:Configuration=Release /p:Platform=AnyCPU /p:BuildProjectReferences=false /p:PostBuildEvent=
    artifacts:
      paths:
        - "Client/bin/Release"

build_linux:
    stage: build_server
    script:
        - cd gtaserver.core
        - dotnet publish -r ubuntu-x64 -c Release -o publish/linux-Release
    artifacts:
        paths:
            - "gtaserver.core/publish/linux-Release"

build_linux_arm:
    stage: build_server
    when: manual
    script:
        - cd gtaserver.core
        - dotnet publish -r linux-arm -c Release -o publish/arm-Release
    artifacts:
        paths:
            - "gtaserver.core/publish/arm-Release"

build_plugins:
    stage: plugins
    script:
       - cd Race
       - dotnet publish -c Release -o publish
       - cd ../DiscordBot # hm
       - dotnet publish -c Release -o publish
    artifacts:
        paths:
            - "Race/publish/race.dll"
            - "Race/publish/race.pdb"
            - "Race/publish/Maps"
            - "DiscordBot/publish/DiscordBot.dll"
            - "DiscordBot/publish/DiscordBot.pdb"
